# Generated by Django 5.1.6 on 2025-03-08 00:53

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('plot', models.TextField(blank=True)),
                ('plot_embedding', django_mongodb_backend.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('poster', models.URLField()),
                ('runtime', models.IntegerField(default=0)),
                ('released', models.DateTimeField(blank=True, null=True, verbose_name='release date')),
                ('genres', django_mongodb_backend.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
            ],
            options={
                'db_table': 'embedded_movies',
                'managed': False,
            },
        ),
    ]
